version: '3.8'

services:
  db:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    environment:
      MYSQL_DATABASE: dratter_react_development
      MYSQL_USER: development
      MYSQL_PASSWORD: Midgardsormr71021
      MYSQL_ROOT_PASSWORD: Midgardsormr71021
    ports:
      - '3307:3306'
    # healthcheck:
    #   test: ["CMD", "mysqladmin" ,"ping", "-h", "8080"]
    #   interval: 1s
    #   retries: 3
    # volumes:
    #   - mysql-volume:/var/lib/mysql

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    # command: ['./wait-for-it.sh', 'db:3306', '--', 'bundle', 'exec', 'rails', 'server']
    volumes:
      - ./backend:/backend
      - /app/vendor
      - /app/tmp
      - /app/log
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_started
    stdin_open: true
    tty: true
    environment:
      DB_PORT: 3306
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: Midgardsormr71021
      RAILS_MAX_THERADS: 5
      RAILS_ENV: development

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
    ports:
      - '3000:3000'